version: "3.8"

networks:
  shared-network:
    external: true # Use external network

services:
  notification-service:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: notification-service
    ports:
      - "8081:8081"
      - "8082:8082"
    networks:
      - shared-network
